### PR TITLE
Optimize 'fold', document blocking caveat of 'duplicate', and fix race in 'receive'

### PR DESCRIPTION
**Pull request by joeyadams**
Please see the commit messages.  In particular, `duplicate` has the same [blocking caveat](http://hackage.haskell.org/trac/ghc/ticket/4154) that bit [isEmptyChan](http://hackage.haskell.org/packages/archive/base/latest/doc/html/Control-Concurrent-Chan.html#v:isEmptyChan) and [unGetChan](http://hackage.haskell.org/packages/archive/base/latest/doc/html/Control-Concurrent-Chan.html#v:unGetChan).

Differences between `unsafeFold` and `fold`:
- `unsafeFold` is _less_ efficient than `fold`; see commit 51871dd
- `unsafeFold` can be used to make multiple threads fight over a single channel, useful for sharing jobs among threads.
- `unsafeFold` breaks referential transparency under base < 4.6 due to `unsafeInterleaveIO` duplicating the computation; see [GHC ticket 5859](http://hackage.haskell.org/trac/ghc/ticket/5859).  Regular `fold` does not have this problem because its interleaved computation does not leave side effects in its wake.

### CODE REVIEW

**Comment by lpsmith** [comment]
Sigh.   Concurrency is hard.

What if `ReceivePort` was a `(MVar (), IORef (List a))` pair?  Duplicate and fold would just read the `IORef`,  whereas pretty much everything else would have to hold the `MVar`.    I don't have time to think this through at the moment,  just spitballing.

**Comment by lpsmith** [comment]
Ok, I think my idea is sound,  you can take a look at it in my [ioref-receiveport](https://github.com/lpsmith/split-channel/tree/ioref-receiveport) branch.

This almost lets us implement `isEmptyChan` and a non-blocking receive as well.    However, isn't there the possibility that `tryTakeMVar` would (erroneously) return `Nothing` when another thread is calling `readMVar`?   This might be another argument for implementing atomic reads.

**Comment by lpsmith** [comment]
Hmm, another thought,  is that I'm not entirely convinced that `unsafeFold` is really all that useful.  I mean, you can already use split-channel as a work distribution mechanism by having multiple readers on the same read port.

**Comment by joeyadams** [comment]
> Ok, I think my idea is sound, you can take a look at it in my ioref-receiveport branch.

Looks good.  In theory, there might be a difference in fairness (`receive`s queue up behind the `ReceivePort` lock, but `fold`s queue up behind the hole), but it's better than blocking in strange situations.

I would rename `withMVarMasked` to `compat_withMVarMasked`, in case a later version of base adds `withMVarMasked`.  That, or use explicit imports for `Control.Concurrent.MVar`.

> This almost lets us implement isEmptyChan and a non-blocking receive as well. However, isn't there the possibility that tryTakeMVar would (erroneously) return Nothing when another thread is calling readMVar? This might be another argument for implementing atomic reads.

Why bother?  I think it'd be better to have an STM alternative.  It would have these operations, but it would not have lazy `fold` (interleaved STM can lead to nested `atomically`).

What would be a good name for such a module?  Perhaps one of:
- `Control.Concurrent.STM.Chan.Split`
- `Data.STM.Chan.Split`
- `Data.STM.SplitChan`

I've taken to using the `Data.STM` prefix in my STM channel libraries (e.g. [stm-sbchan](http://hackage.haskell.org/package/stm-sbchan)).  It's less verbose, and might be more appropriate since a channel is just a mutable structure in STM, much like a linked list in C.

Should this be in the split-channel package, or in a separate package?  Either way, I volunteer to implement it.

> Hmm, another thought, is that I'm not entirely convinced that unsafeFold is really all that useful. I mean, you can already use split-channel as a work distribution mechanism by having multiple readers on the same read port.

Agreed.  I guess we should remove or deprecate it.

**Comment by lpsmith** [comment]
I think it an stm-split-channel should probably be a separate package;  and by all means go for it!

Yeah,   I uploaded 0.2 a while ago,  with your changes + my modifications to the `ReceivePort` structure.  I also removed `unsafeFold`;  another justification is that it can be implemented with the public interface if somebody really wants it.

As for implementing `isEmptyChan`,  why not?   It'd be a little interesting if we could correctly implement it, and it might be useful.

**Comment by lpsmith** [comment]
Oh, I don't think there's any _serious_ fairness problems here:   readers on the list only ever use `readMVar`, which means there should normally be minimal contention for list `MVar`s.

**Comment by joeyadams** [comment]
I don't think `isEmptyChan` can be implemented correctly without changing the internal representation.  As you noticed, other readers rolling through the list will intermittently cause `tryTakeMVar` to return `Nothing` while an item is being borrowed.

**Comment by lpsmith** [comment]
My point being that `isEmptyChan` couldn't be properly implemented until [GHC issue #4001](http://hackage.haskell.org/trac/ghc/ticket/4001) is fixed.

**Comment by hvr** [comment]
> I would rename `withMVarMasked` to `compat_withMVarMasked`, in case a later version of base adds `withMVarMasked`. That, or use explicit imports for `Control.Concurrent.MVar`.

Fyi, that exactly is happening in GHC 7.8 with ghc/packages-base@a91d68221ca30a3564 :-)

**Comment by lpsmith** [comment]
Thanks for the heads up,  but `withMVarMasked` was changed to `withLock` in 05907d71b91579b2a64c50e16d594c459998b8e8.  =)

**Pull request merged**
